name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Extract App Version
      run: |
        export APP_VERSION=$(jq -r '.version' package.json)
        echo "App version is $APP_VERSION"
          
    - name: Build the Docker image
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} ${{secrets.DOCKER_SERVER}}
        docker build -t node-image:latest .
        docker image tag node-image:latest ${{secrets.DOCKER_SERVER}}/node-image:$APP_VERSION
        docker image push ${{secrets.DOCKER_SERVER}}/node-image:latest
