name: Docker Image CI

env:
  TEST_ENV: ""
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Extract App Version
      id: step1
      run: |
        APP_VERSION=$(jq -r '.version' package.json)
        echo "App version is $APP_VERSION"
        echo "::set-output name=output::$APP_VERSION"
          
    - name: Build the Docker image
      id: step2
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} ${{secrets.DOCKER_SERVER}}
        docker build -t node-image:${{ steps.step1.outputs.output }} .
        docker image tag node-image:${{ steps.step1.outputs.output }} ${{secrets.DOCKER_SERVER}}/node-image:${{ steps.step1.outputs.output }}
        docker image push ${{secrets.DOCKER_SERVER}}/node-image:${{ steps.step1.outputs.output }}
